test

diff --git a/.github/workflows/build and deploy.yml b/.github/workflows/build and deploy.yml
--- a/.github/workflows/build and deploy.yml
+++ b/.github/workflows/build and deploy.yml
@@ -93,20 +93,27 @@ jobs:
           fi
         shell: bash
 
+      # - name: Parse .env File and Fetch Secrets with envsubst
+      #   run: |
+      #     echo "Using environment file: $ENV_FILE"
+      #     grep -v '^#' $ENV_FILE | grep -v '^[[:space:]]*$' | while read -r line; do
+      #       if [[ $line =~ \${([^}]+)} ]]; then
+      #         var_name="${BASH_REMATCH[1]}"
+      #         if [ -z "${!var_name}" ]; then
+      #           echo "Error: Secret $var_name not found in GitHub Secrets"
+      #           exit 1
+      #         fi
+      #       fi
+      #     done
+      #     grep -v '^#' $ENV_FILE | grep -v '^[[:space:]]*$' | envsubst > parsed_env
+      #     cat parsed_env
+      #   shell: bash
       - name: Parse .env File and Fetch Secrets with envsubst
         run: |
           echo "Using environment file: $ENV_FILE"
-          grep -v '^#' $ENV_FILE | grep -v '^[[:space:]]*$' | while read -r line; do
-            if [[ $line =~ \${([^}]+)} ]]; then
-              var_name="${BASH_REMATCH[1]}"
-              if [ -z "${!var_name}" ]; then
-                echo "Error: Secret $var_name not found in GitHub Secrets"
-                exit 1
-              fi
-            fi
-          done
+          export $(grep -v '^#' $ENV_FILE | xargs)  # Загружаем все переменные из файла в окружение
           grep -v '^#' $ENV_FILE | grep -v '^[[:space:]]*$' | envsubst > parsed_env
-          cat parsed_env
+          cat parsed_env  # Проверяем результат
         shell: bash
 
       - name: Pull and restart Docker container
